services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata2:/var/lib/postgresql/data
    ports:
      - "{DB_EXT_PORT}:5432"

  fastapi:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "{FASTAPI_PORT}:8000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    env_file:
      - stack.env

volumes:
  pgdata2:
